//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tellurian.Trains.Planning.App.Contracts.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Notes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Notes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tellurian.Trains.Planning.App.Contracts.Resources.Notes", typeof(Notes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All destinations.
        /// </summary>
        public static string AllDestinations {
            get {
                return ResourceManager.GetString("AllDestinations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        public static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} and beyond.
        /// </summary>
        public static string AndBeyond {
            get {
                return ResourceManager.GetString("AndBeyond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrival.
        /// </summary>
        public static string Arrival {
            get {
                return ResourceManager.GetString("Arrival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocking service.
        /// </summary>
        public static string BlockingService {
            get {
                return ResourceManager.GetString("BlockingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brings no wagons from this station.
        /// </summary>
        public static string BringsNoWagonsFromThisStation {
            get {
                return ResourceManager.GetString("BringsNoWagonsFromThisStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brings wagons to {0}..
        /// </summary>
        public static string BringsWaggonsToDestinations {
            get {
                return ResourceManager.GetString("BringsWaggonsToDestinations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargo.
        /// </summary>
        public static string Cargo {
            get {
                return ResourceManager.GetString("Cargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargo turnus.
        /// </summary>
        public static string CargoTurnus {
            get {
                return ResourceManager.GetString("CargoTurnus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carrier.
        /// </summary>
        public static string Carrier {
            get {
                return ResourceManager.GetString("Carrier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circulate loco..
        /// </summary>
        public static string CirculateLoco {
            get {
                return ResourceManager.GetString("CirculateLoco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Circulate loco..
        /// </summary>
        public static string CirculateLocoDays {
            get {
                return ResourceManager.GetString("CirculateLocoDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        public static string Class {
            get {
                return ResourceManager.GetString("Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commuter train.
        /// </summary>
        public static string CommuterTrain {
            get {
                return ResourceManager.GetString("CommuterTrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect {0}..
        /// </summary>
        public static string ConnectTrainset {
            get {
                return ResourceManager.GetString("ConnectTrainset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consignee.
        /// </summary>
        public static string Consignee {
            get {
                return ResourceManager.GetString("Consignee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contruction train.
        /// </summary>
        public static string ConstructionTrain {
            get {
                return ResourceManager.GetString("ConstructionTrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container train.
        /// </summary>
        public static string ContainerTrain {
            get {
                return ResourceManager.GetString("ContainerTrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continues as train {0} to {1}..
        /// </summary>
        public static string ContinuesAsTrainToDestination {
            get {
                return ResourceManager.GetString("ContinuesAsTrainToDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continues {2} as train {0} to {1}..
        /// </summary>
        public static string ContinuesDaysAsTrainToDestination {
            get {
                return ResourceManager.GetString("ContinuesDaysAsTrainToDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily.
        /// </summary>
        public static string Daily {
            get {
                return ResourceManager.GetString("Daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily.
        /// </summary>
        public static string DailyShort {
            get {
                return ResourceManager.GetString("DailyShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPPER.
        /// </summary>
        public static string DayNameCasing {
            get {
                return ResourceManager.GetString("DayNameCasing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departure.
        /// </summary>
        public static string Departure {
            get {
                return ResourceManager.GetString("Departure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination.
        /// </summary>
        public static string Destination {
            get {
                return ResourceManager.GetString("Destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} in {1}.
        /// </summary>
        public static string DestinationInCountry {
            get {
                return ResourceManager.GetString("DestinationInCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect wagons continuing in other trains..
        /// </summary>
        public static string DisconnectContinuingWagons {
            get {
                return ResourceManager.GetString("DisconnectContinuingWagons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect {0}..
        /// </summary>
        public static string DisconnectTrainset {
            get {
                return ResourceManager.GetString("DisconnectTrainset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect wagons to {0}..
        /// </summary>
        public static string DisconnectWagonsToHere {
            get {
                return ResourceManager.GetString("DisconnectWagonsToHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect wagons to {0} and beyond..
        /// </summary>
        public static string DisconnectWagonsToHereAndFurther {
            get {
                return ResourceManager.GetString("DisconnectWagonsToHereAndFurther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Train driver.
        /// </summary>
        public static string Driver {
            get {
                return ResourceManager.GetString("Driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duty.
        /// </summary>
        public static string Duty {
            get {
                return ResourceManager.GetString("Duty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty train.
        /// </summary>
        public static string EmptyTrain {
            get {
                return ResourceManager.GetString("EmptyTrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine change from {0} to {1}..
        /// </summary>
        public static string EngineChange {
            get {
                return ResourceManager.GetString("EngineChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {2}: Engine change from {0} to {1}..
        /// </summary>
        public static string EngineChangeDays {
            get {
                return ResourceManager.GetString("EngineChangeDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Epoch.
        /// </summary>
        public static string Epoch {
            get {
                return ResourceManager.GetString("Epoch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Express train.
        /// </summary>
        public static string ExpressTrain {
            get {
                return ResourceManager.GetString("ExpressTrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Express freight train.
        /// </summary>
        public static string FreightExpressTrain {
            get {
                return ResourceManager.GetString("FreightExpressTrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freight train.
        /// </summary>
        public static string FreightTrain {
            get {
                return ResourceManager.GetString("FreightTrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        public static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fr.
        /// </summary>
        public static string FridayShort {
            get {
                return ResourceManager.GetString("FridayShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get {0} at parking area..
        /// </summary>
        public static string GetLocoAtParking {
            get {
                return ResourceManager.GetString("GetLocoAtParking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1}: Get {0} at parking area..
        /// </summary>
        public static string GetLocoAtParkingOnDays {
            get {
                return ResourceManager.GetString("GetLocoAtParkingOnDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historical train.
        /// </summary>
        public static string HistoricalTrain {
            get {
                return ResourceManager.GetString("HistoricalTrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions.
        /// </summary>
        public static string Instructions {
            get {
                return ResourceManager.GetString("Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InterCity.
        /// </summary>
        public static string InterCity {
            get {
                return ResourceManager.GetString("InterCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InterRegio.
        /// </summary>
        public static string InterRegio {
            get {
                return ResourceManager.GetString("InterRegio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping.
        /// </summary>
        public static string IsStopping {
            get {
                return ResourceManager.GetString("IsStopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is throughpassing.
        /// </summary>
        public static string IsThroughpassing {
            get {
                return ResourceManager.GetString("IsThroughpassing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load {0}..
        /// </summary>
        public static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local destinations.
        /// </summary>
        public static string LocalDestinations {
            get {
                return ResourceManager.GetString("LocalDestinations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local freight train.
        /// </summary>
        public static string LocalFreightTrain {
            get {
                return ResourceManager.GetString("LocalFreightTrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local train.
        /// </summary>
        public static string LocalTrain {
            get {
                return ResourceManager.GetString("LocalTrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loco.
        /// </summary>
        public static string Loco {
            get {
                return ResourceManager.GetString("Loco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loco transport.
        /// </summary>
        public static string LocoTransport {
            get {
                return ResourceManager.GetString("LocoTransport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loco turnus.
        /// </summary>
        public static string LocoTurnus {
            get {
                return ResourceManager.GetString("LocoTurnus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long-distance freight train.
        /// </summary>
        public static string LongDistanceFreightTrain {
            get {
                return ResourceManager.GetString("LongDistanceFreightTrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail train.
        /// </summary>
        public static string MailTrain {
            get {
                return ResourceManager.GetString("MailTrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meets {0}..
        /// </summary>
        public static string MeetsOtherTrains {
            get {
                return ResourceManager.GetString("MeetsOtherTrains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mixed train.
        /// </summary>
        public static string MixedTrain {
            get {
                return ResourceManager.GetString("MixedTrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        public static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mo.
        /// </summary>
        public static string MondayShort {
            get {
                return ResourceManager.GetString("MondayShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move continuing wagons to departure tracks..
        /// </summary>
        public static string MoveContinuingWagonsToDepartureTracks {
            get {
                return ResourceManager.GetString("MoveContinuingWagonsToDepartureTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move rest of the wagons to the table..
        /// </summary>
        public static string MoveRestOfWagonsToTable {
            get {
                return ResourceManager.GetString("MoveRestOfWagonsToTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night train.
        /// </summary>
        public static string NightTrain {
            get {
                return ResourceManager.GetString("NightTrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal freight train.
        /// </summary>
        public static string NormalFreightTrain {
            get {
                return ResourceManager.GetString("NormalFreightTrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No stop..
        /// </summary>
        public static string NoStop {
            get {
                return ResourceManager.GetString("NoStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On demand.
        /// </summary>
        public static string OnDemand {
            get {
                return ResourceManager.GetString("OnDemand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demand.
        /// </summary>
        public static string OnDemandShort {
            get {
                return ResourceManager.GetString("OnDemandShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator.
        /// </summary>
        public static string Operator {
            get {
                return ResourceManager.GetString("Operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ore train.
        /// </summary>
        public static string OreTrain {
            get {
                return ResourceManager.GetString("OreTrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origin.
        /// </summary>
        public static string Origin {
            get {
                return ResourceManager.GetString("Origin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passenger train.
        /// </summary>
        public static string PassengerTrain {
            get {
                return ResourceManager.GetString("PassengerTrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive {0} to parking area..
        /// </summary>
        public static string PutLocoAtParking {
            get {
                return ResourceManager.GetString("PutLocoAtParking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1}: Drive {0} to parking area..
        /// </summary>
        public static string PutLocoAtParkingAtDays {
            get {
                return ResourceManager.GetString("PutLocoAtParkingAtDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Railcar.
        /// </summary>
        public static string Railcar {
            get {
                return ResourceManager.GetString("Railcar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Railcar turnus.
        /// </summary>
        public static string RailcarTurnus {
            get {
                return ResourceManager.GetString("RailcarTurnus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regional train.
        /// </summary>
        public static string RegionalTrain {
            get {
                return ResourceManager.GetString("RegionalTrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        public static string Remarks {
            get {
                return ResourceManager.GetString("Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse loco..
        /// </summary>
        public static string ReverseLoco {
            get {
                return ResourceManager.GetString("ReverseLoco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        public static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sa.
        /// </summary>
        public static string SaturdayShort {
            get {
                return ResourceManager.GetString("SaturdayShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipper.
        /// </summary>
        public static string Shipper {
            get {
                return ResourceManager.GetString("Shipper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shunting.
        /// </summary>
        public static string Shunting {
            get {
                return ResourceManager.GetString("Shunting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special freight train.
        /// </summary>
        public static string SpecialFreightTrain {
            get {
                return ResourceManager.GetString("SpecialFreightTrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed train.
        /// </summary>
        public static string SpeedTrain {
            get {
                return ResourceManager.GetString("SpeedTrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station.
        /// </summary>
        public static string Station {
            get {
                return ResourceManager.GetString("Station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        public static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Su.
        /// </summary>
        public static string SundayShort {
            get {
                return ResourceManager.GetString("SundayShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch wagons to cargo customers..
        /// </summary>
        public static string SwitchWagonsToCustomers {
            get {
                return ResourceManager.GetString("SwitchWagonsToCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        public static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Th.
        /// </summary>
        public static string ThursdayShort {
            get {
                return ResourceManager.GetString("ThursdayShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timber train.
        /// </summary>
        public static string TimberTrain {
            get {
                return ResourceManager.GetString("TimberTrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track.
        /// </summary>
        public static string Track {
            get {
                return ResourceManager.GetString("Track", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Train.
        /// </summary>
        public static string Train {
            get {
                return ResourceManager.GetString("Train", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Train clearance.
        /// </summary>
        public static string TrainClearance {
            get {
                return ResourceManager.GetString("TrainClearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (via {1}).
        /// </summary>
        public static string TransferVia {
            get {
                return ResourceManager.GetString("TransferVia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        public static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu.
        /// </summary>
        public static string TuesdayShort {
            get {
                return ResourceManager.GetString("TuesdayShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn and reverse loco..
        /// </summary>
        public static string TurnAndReverseLoco {
            get {
                return ResourceManager.GetString("TurnAndReverseLoco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn loco..
        /// </summary>
        public static string TurnLoco {
            get {
                return ResourceManager.GetString("TurnLoco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turnus.
        /// </summary>
        public static string Turnus {
            get {
                return ResourceManager.GetString("Turnus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unload {0}..
        /// </summary>
        public static string Unload {
            get {
                return ResourceManager.GetString("Unload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use {0}..
        /// </summary>
        public static string UseLoco {
            get {
                return ResourceManager.GetString("UseLoco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1}: Use {0}..
        /// </summary>
        public static string UseLocoAtDays {
            get {
                return ResourceManager.GetString("UseLocoAtDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid {0:d} - {1:d}.
        /// </summary>
        public static string ValidPeriod {
            get {
                return ResourceManager.GetString("ValidPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule.
        /// </summary>
        public static string VehicleScheduleNumber {
            get {
                return ResourceManager.GetString("VehicleScheduleNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wagonset.
        /// </summary>
        public static string Wagonset {
            get {
                return ResourceManager.GetString("Wagonset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wagonset turnus.
        /// </summary>
        public static string WagonsetTurnus {
            get {
                return ResourceManager.GetString("WagonsetTurnus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wagon turnus.
        /// </summary>
        public static string WagonTurnus {
            get {
                return ResourceManager.GetString("WagonTurnus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        public static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We.
        /// </summary>
        public static string WednesdayShort {
            get {
                return ResourceManager.GetString("WednesdayShort", resourceCulture);
            }
        }
    }
}
